### ISSUE TITLE
Typo in default exe name

### ISSUE THREAD

**Issue by ghost** [timtro/glslView-nvim#5]
Commit ecc739d8e582ed751f12f54f5b1957f1ef057d3e changed the default exe path in `lua/glslView.lua` to `glslView` but it should be `glslViewer`.

**Comment by timtro** [comment]
Thanks. I haven't played with shaders in a bit. After struggling with some health problems, I've been burning hard to finish a PhD thesis.

I wrote this plugin, not really expecting anyone to use it :)

Now that I know people are, I'm going to redo it properly and provide a `setup` function for configuration.

**Comment by timtro** [comment]
I just merged a series of changes, 24f8d90. Changes include the update to the default viewer binary path and updated readme.

Thanks for posting the issue.

If you find any problems, or it isn't fixed for you, feel free to reopen or open a new issue.
